exports.ApplicationInfo_WebElements = 
class ApplicationInfo_WebElements
{
    constructor() 
    {
        this.VehicleWorth_Field = "//label[text()='What do you estimate this vehicle to be worth?']/following-sibling::div[1]/input"
        this.ReserveType_Dropdown = "//span[text()='Reserve type']/../following-sibling::button"
        this.Reserve = "//span[text()='Reserve']/parent::div"
        this.ConsignmentSpecialist = "//span[text()='Are you currently working with a consignment specialist?']/../following-sibling::button"
        this.Select_ConsignmentSpecialist = "//div[@dir='ltr']/div/div[1]"
        this.AnothweAuction = "//span[text()='Would you consider consigning at another one of our auctions?']/../following-sibling::button"
        this.SelectYes = "//span[text()='Yes']/parent::div"

        this.SignatureName = "//input[@name='name']"
        this.Calendar = "//button[@aria-label='Calendar']"
        this.CurrentDate = "//div[contains(@aria-label,'Today')]"
        this.SubmitApplicaion = "//span[text()='Submit application']/parent::button"

        this.ViewSubmission = "//span[text()='View my submission']/parent::a"
        this.Consignmentbutton = "//div[text()='Consignments']/parent::div"
        this.FormLibrary = "//span[text()='Form Library']/parent::a"
        this.Filterbutton = "//button[text()='Filter']"
        this.RemovePastEvent = "//span[text()='Event: Scottsdale 2026']/../parent::button"

        //Dashboard
        this.Consignmentbutton = "//div[text()='Consignments']/parent::div"
        this.SelectFirstVehicle = "(//div[contains(@class,'view')]/div[text()='View'])[1]"
        this.Modifield_Horsepower_Text = "//p[text()='Vehicle details']/parent::div/ul/li/div[text()='Modified horsepower']"
        this.ShortDescription = "//div[@aria-label='Consignment details']/a[contains(@id,'description')][1]"
        this.LongDescription = "//div[@aria-label='Consignment details']/a[contains(@id,'long-description')]"
        this.MediaTab = "//div[@aria-label='Consignment details']/a[contains(@id,'media')]"
        this.UploadMedia_Button = "//button[text()='Upload media']"
        this.AdditionalPhotos = "//input[@type='file']"
        this.Upload_Button = "//button[text()='Upload']"
        this.UploadAll_Button = "//button[text()='Cancel']/following-sibling::button"
        this.DocumentTab = "//div[@aria-label='Consignment details']/a[contains(@id,'documents')]"
        this.IndividualDocumentSection = "//div[@aria-label='Consignment details']/a[contains(@id,'individual')]"
        this.FirstDocument = "(//p[text()='Choose document'])[1]"
        this.SecondDocument = "(//p[text()='Choose document'])[2]"
        this.ThirdDocument = "(//p[text()='Choose document'])[3]"
        this.BusinessDocumentSection = "//div[@aria-label='Consignment details']/a[contains(@id,'business')]"
        this.ApplicantInfoTab = "//div[@aria-label='Consignment details']/a[contains(@id,'applicant')]"
        this.Applicant_Address = "//div[@aria-label='Consignment details']/a[contains(@id,'addresses')]"

        this.MyAccount_Button = "//div[text()='My Account']/parent::button"
        this.ViewAccount = "//div[text()='View account']/parent::div/parent::a"
        this.EditAccount = "//button[text()='Edit Account']"
        this.Close_ViewAccount = "//h2[@slot='title']/following-sibling::button"
        this.Document = "//div[text()='Documents']/parent::div/parent::a"
        this.Passport_Document = "//a[contains(@href,'document=10')]"
        this.Insurance_Document = "//a[contains(@href,'document=6')]"
        this.DriverLicense_Document = "//a[contains(@href,'document=4')]"
        this.Bank_Document = "//a[contains(@href,'document=5')]"
        this.AdditionalBankLetter_Document = "//a[contains(@href,'document=11')]"
        this.Business_Document = "//a[contains(@href,'business')]"
        this.Addresses = "//div[text()='Addresses']/parent::div/parent::a"
        this.AddNew_Address = "//button[text()='Add new']"
        this.MallingAddress = "(//input[@name='addressSearch'])[1]"
        this.SelectAddress = "(//div[contains(@data-key, 'address.')])[1]"
        this.RetrySearch = "//button[text()='Retry search']"
        this.AddressType_Dropdowm = "//span[text()='Address type']/following-sibling::button"
        this.Mailing = "//label[text()='Mailing']"
        this.VehicleTitiling = "//label[text()='Vehicle Titling']"
        this.TitlePaperwork = "//label[text()='Title Paperwork']"
        this.BiddingColl = "//label[text()='Bidding Collateral Return']"
        this.ProceedPayment = "//label[text()='Proceeds Payment']"
        this.CloseDropdown = "//div[@dir='ltr']"
        this.AddressType_Text = "//span[text()='Address type']"
        this.SaveChanges = "//button[text()='Save changes']"
    }
}
